### ISSUE TITLE
Missing notes

### ISSUE THREAD

**Issue by falkTX** [sfztools/sfizz#2]
Not sure if it happens in the JACK client or the SFZ engine, but compared to other sfz players I notice a definitive lack of notes played when using a few SFZs I have around.

This is one such case https://musical-artifacts.com/artifacts/460

Is there a polyphony limit? If so, it seems very low.

**Comment by paulfd** [comment]
There is, it's hardcoded (well, compile-time constant, for now) at 64 voices, which should be healthy for simple pieces. There may be other issues. What do you use to compare?

**Comment by falkTX** [comment]
I am just playing simple midi files, not a lot of notes in there really

**Comment by paulfd** [comment]
One (big) issue that is appearing quickly is that the paths in the sfz file do not have the proper case, which is really not helping :sweat_smile: This is for the demo version at least.

The fact that you heard anything at all is surprising actually. The output for the command for me is:
```
Removed 1032 out of 1032 regions.
==========
Total:
        Masters: 1
        Groups: 250
        Regions: 0
        Curves: 0
        PreloadedSamples: 0
```
Which means nothing is loaded and no regions will be triggered.
